# Generated by Django 4.2.20 on 2025-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_responded',
            field=models.BooleanField(default=False, verbose_name='پاسخ داده شده'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='telegram_response',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ تلگرام'),
        ),
    ]
