# Generated by Django 4.2.20 on 2025-03-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('link', models.CharField(max_length=200, verbose_name='لینک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس محصول')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/ غیرفعال')),
                ('link_preview_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='تصویر پیش\u200cنمایش لینک')),
                ('link_preview_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان پیش\u200cنمایش لینک')),
                ('link_preview_description', models.TextField(blank=True, null=True, verbose_name='توضیحات پیش\u200cنمایش لینک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('views', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='برچسب\u200cها')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'سایت',
                'verbose_name_plural': 'سایت ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
