# Generated by Django 4.2.20 on 2025-03-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link_preview_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='link_preview_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='link_preview_title',
        ),
    ]
